# Generated by Django 5.1 on 2024-08-30 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_multiplechoicequestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='multiplechoicequestion',
            name='correct_option',
            field=models.CharField(choices=[('A', 'Option A'), ('B', 'Option B'), ('C', 'Option C'), ('D', 'Option D')], default='A', max_length=1),
        ),
        migrations.AddField(
            model_name='multiplechoicequestion',
            name='option_a',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='multiplechoicequestion',
            name='option_b',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='multiplechoicequestion',
            name='option_c',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='multiplechoicequestion',
            name='option_d',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='multiplechoicequestion',
            name='question',
            field=models.TextField(default='', max_length=200),
        ),
    ]
