# Generated by Django 5.1 on 2024-08-30 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_multiplechoicequestion_correct_option_and_more'),
        ('quiz', '0003_quiz_join_code'),
    ]

    operations = [
    ]
