# Generated by Django 5.1 on 2024-10-04 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0007_quiz_participants'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='finished',
            field=models.BooleanField(default=False),
        ),
    ]
