# Generated by Django 5.1 on 2024-10-20 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0011_alter_quiz_current_question'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='finished',
        ),
    ]
