# Generated by Django 5.1 on 2024-10-22 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0012_remove_quiz_finished'),
    ]

    operations = [
        migrations.AddField(
            model_name='multiplechoicequestion',
            name='credits',
            field=models.PositiveIntegerField(default=10),
        ),
    ]
